# Maintained C uses exact ICK source c61e448251744a2f40ad743ebef1a027bdcd2f9d.
# Foreign libraries, NDK assembly and platform linking retain their declared roles.
.DEFAULT_GOAL := all
ROOT ?= $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../..)
OUTPUT ?= $(ROOT)/work/native
PLATFORM ?= host
PROTOCOL ?= 2
ICK ?=
ICK_FLAGS ?=
NDK ?=
PREFIX = $(OUTPUT)/prefix
NDK_HOST = $(NDK)/toolchains/llvm/prebuilt/linux-x86_64
NDK_BIN = $(NDK_HOST)/bin
BUILTIN = $(shell "$(ICK)" $(ICK_FLAGS) -print-file-name=include)
CFLAGS = -std=c11 -Os -fPIC -Wall -Wextra -Werror -DCURL_STATICLIB -I"$(PREFIX)/include" -I"$(ROOT)/transport/native"
PLATFORM_DRIVER = $(NDK_BIN)/clang
SYSTEM_LIBS = -ldl -pthread -lm
ifeq ($(PLATFORM),a1)
PLATFORM_DRIVER = $(NDK_BIN)/armv7a-linux-androideabi24-clang
CFLAGS += --sysroot="$(NDK_HOST)/sysroot" -nostdinc -isystem "$(BUILTIN)" -isystem "$(NDK_HOST)/sysroot/usr/include" -isystem "$(NDK_HOST)/sysroot/usr/include/arm-linux-androideabi" -D__ANDROID__ -D__ANDROID_API__=24 -D__ANDROID_MIN_SDK_VERSION__=24 -DBIONIC_IOCTL_NO_SIGNEDNESS_OVERLOAD -marm -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16
SYSTEM_LIBS = -ldl -pthread
endif
LIBRARIES = $(PREFIX)/lib/libcurl.a $(PREFIX)/lib/libnghttp2.a
ifeq ($(PROTOCOL),3)
LIBRARIES += $(PREFIX)/lib/libngtcp2_crypto_ossl.a $(PREFIX)/lib/libngtcp2.a $(PREFIX)/lib/libnghttp3.a
endif
LIBRARIES += $(PREFIX)/lib/libssl.a $(PREFIX)/lib/libcrypto.a
OBJECTS = $(addprefix $(OUTPUT)/owned-c/,curl_transport.o sse.o provider_framing.o)

.PHONY: all check framing FORCE
FORCE:
all: check $(OUTPUT)/libfastchat_transport.so $(OUTPUT)/fastchat-transport-probe
check:
	test -x "$(ICK)"
	test -x "$(PLATFORM_DRIVER)"
	test "$(PLATFORM)" = host || test "$(PLATFORM)" = a1
	test "$(PROTOCOL)" = 2 || test "$(PROTOCOL)" = 3
	test -f "$(BUILTIN)/stddef.h"
	mkdir -p "$(OUTPUT)/owned-c"

$(OUTPUT)/owned-c/%.s: $(ROOT)/transport/native/%.c FORCE | check
	"$(ICK)" $(ICK_FLAGS) $(CFLAGS) -S "$<" -o "$@"
$(OUTPUT)/owned-c/probe.s: $(ROOT)/examples/autogenerated/http-transport/probe.c FORCE | check
	"$(ICK)" $(ICK_FLAGS) $(CFLAGS) -S "$<" -o "$@"
$(OUTPUT)/owned-c/framing-test.s: $(ROOT)/examples/autogenerated/http-transport/framing-test.c FORCE | check
	"$(ICK)" $(ICK_FLAGS) $(CFLAGS) -S "$<" -o "$@"
$(OUTPUT)/owned-c/%.o: $(OUTPUT)/owned-c/%.s
	"$(PLATFORM_DRIVER)" -fPIC -c "$<" -o "$@"

$(OUTPUT)/libfastchat_transport.so: $(OBJECTS)
	"$(PLATFORM_DRIVER)" -shared -Wl,--no-undefined -Wl,--exclude-libs,ALL $^ $(LIBRARIES) $(SYSTEM_LIBS) -o "$@"
$(OUTPUT)/fastchat-transport-probe: $(OUTPUT)/owned-c/probe.o $(OBJECTS)
	"$(PLATFORM_DRIVER)" $^ $(LIBRARIES) $(SYSTEM_LIBS) -o "$@"
framing: $(OUTPUT)/owned-c/framing-test.o $(OUTPUT)/owned-c/sse.o $(OUTPUT)/owned-c/provider_framing.o
	test "$(PLATFORM)" = host
	"$(PLATFORM_DRIVER)" $^ -o "$(OUTPUT)/framing-test"
	"$(OUTPUT)/framing-test"
.SECONDARY:
